package com.azzahid.hof.domain.state

import android.net.Uri
import io.ktor.http.HttpMethod


data class FileSystemRouteUiState(
    val path: String = "",
    val shareName: String = "",
    val selectedFile: FileSelection? = null,
    val respectIndexHtml: Boolean = true,
    val isValid: Boolean = false,
    val isPathAutoGenerated: Boolean = true
)

data class FileSelection(
    val uri: Uri? = null,
    val displayName: String = "",
    val isDirectory: Boolean = false
)

data class HeaderEntry(
    val key: String = "",
    val value: String = ""
)

data class ApiRouteUiState(
    val path: String = "",
    val method: HttpMethod = HttpMethod.Get,
    val description: String = "",
    val responseBody: String = "{}",
    val statusCode: String = "200",
    val headers: List<HeaderEntry> = listOf(HeaderEntry()),
    val isValid: Boolean = false
) {
    val headersMap: Map<String, String>
        get() = headers.filter { it.key.isNotBlank() }.associate { it.key to it.value }
}